name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: docker build . -t imenbadadi/cloud-s1:5.0.0
      - name: Run the Docker image
        run: docker run -t imenbadadi/cloud-s1:5.0.0
      - name: Push the Docker image
        run: docker push imenbadadi/cloud-s1:5.0.0
